name: Build Tremolo Viola Plugin

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          brew update
          brew install wget cmake
          
      - name: Download and Extract JUCE
        run: |
          # Download the latest JUCE source
          wget https://github.com/juce-framework/JUCE/archive/refs/heads/master.zip -O juce.zip
          unzip juce.zip
          mv JUCE-master JUCE
          
      - name: Build Projucer
        run: |
          # Navigate to the Projucer build directory and build it in Release mode
          cd JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj -configuration "Release" -jobs 4
          
      - name: Move Projucer to Convenient Location
        run: |
          # Copy the Projucer executable to a location that's easier to access
          mkdir -p bin
          cp JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer bin/
          chmod +x bin/Projucer
          
      - name: Create Project with Projucer
        run: |
          # Get the absolute path to the Projucer executable
          PROJUCER_PATH=$(pwd)/bin/Projucer
          
          # Ensure we're at the repository root
          cd $GITHUB_WORKSPACE
          
          # Debugging: list contents of current and project directories
          echo "Contents of current directory:"
          ls -la
          echo "Contents of QuackerVST directory:"
          ls -la QuackerVST || echo "QuackerVST directory not found"
          
          # Resave the .jucer file and override the module path so it points to JUCE/modules
          "$PROJUCER_PATH" --resave "QuackerVST/QuackerVST.jucer" --set-global-module-path "$(pwd)/JUCE/modules"
          
          # Create the Builds directory if it doesn't exist
          mkdir -p Builds/MacOSX
          
          # Export the Xcode project with the correct module path
          "$PROJUCER_PATH" --export-xcode "QuackerVST/QuackerVST.jucer" --set-global-module-path "$(pwd)/JUCE/modules" "Builds/MacOSX"
        
      - name: Build Plugin
        run: |
          # Navigate to the exported Xcode project directory and build it in Release mode
          cd Builds/MacOSX
          echo "Contents of Builds/MacOSX:"
          ls -la
          xcodebuild -project TremoloViolaVST.xcodeproj -configuration "Release" -jobs 4
          
      - name: Package Plugin
        run: |
          # Create directories for packaging plugin outputs
          mkdir -p package/VST3
          mkdir -p package/AU
          
          # Debug output: list build output directory
          echo "Contents of build directory:"
          ls -la Builds/MacOSX/build/Release || echo "Build directory not found"
          
          # Copy built plugins to the package directory
          cp -R Builds/MacOSX/build/Release/TremoloViola.vst3 package/VST3/ || echo "VST3 not found"
          cp -R Builds/MacOSX/build/Release/TremoloViola.component package/AU/ || echo "AU not found"
          
          # Package the plugins into a zip file
          cd package
          zip -r TremoloViola_Mac.zip .
          mv TremoloViola_Mac.zip ../
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TremoloViola_Mac
          path: TremoloViola_Mac.zip
          retention-days: 30
