name: Build QuackerVST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Download JUCE
        run: |
          git clone --depth 1 https://github.com/juce-framework/JUCE.git

      - name: Build Projucer
        run: |
          cd JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -scheme Projucer -configuration Release

      - name: Resave .jucer file
        run: |
          JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer --resave QuackerVST/QuackerVST.jucer

      - name: Export Xcode project
        run: |
          JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer --set-exporter Xcode --resave QuackerVST/QuackerVST.jucer

      - name: Build plugin
        run: |
          cd QuackerVST/Builds/MacOSX
          xcodebuild -configuration Release

      - name: Package build
        run: |
          cd QuackerVST/Builds/MacOSX/build/Release
          zip -r QuackerVST.zip *.vst3 *.component *.au

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuackerVST-macOS
          path: QuackerVST/Builds/MacOSX/build/Release/QuackerVST.zip
