name: Build Tremolo Viola Plugin

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          brew update
          brew install wget cmake
          
      - name: Download and Extract JUCE
        run: |
          # Download latest JUCE
          wget https://github.com/juce-framework/JUCE/archive/refs/heads/master.zip -O juce.zip
          unzip juce.zip
          mv JUCE-master JUCE
          
      - name: Build Projucer
        run: |
          # Navigate to Projucer directory and build
          cd JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj -configuration "Release" -jobs 4
          
      - name: Move Projucer to Convenient Location
        run: |
          # Make Projucer accessible
          mkdir -p bin
          cp JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer bin/
          chmod +x bin/Projucer
      
      - name: Debug Directory Structure
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of QuackerVST directory:"
          ls -la QuackerVST || echo "QuackerVST directory not found"
      
      - name: Update JUCE Module Paths in Jucer File
        run: |
          # Create a modified copy of the .jucer file with updated module paths
          JUCER_FILE="QuackerVST/QuackerVST.jucer"
          JUCE_MODULES_PATH="$(pwd)/JUCE/modules"
          
          # Replace the module paths in the .jucer file
          sed -i '' "s|path=\".*JUCE/modules\"|path=\"$JUCE_MODULES_PATH\"|g" "$JUCER_FILE"
          
          # Verify the change
          echo "Modified .jucer file:"
          cat "$JUCER_FILE"
          
      - name: Create Project with Projucer
        run: |
          # Get the absolute path to the Projucer executable
          PROJUCER_PATH=$(pwd)/bin/Projucer
          
          # Navigate to the root of the repository
          cd $GITHUB_WORKSPACE
          
          # Use the correct path to the .jucer file
          "$PROJUCER_PATH" --resave "QuackerVST/QuackerVST.jucer"
          
          # Create the Builds directory if it doesn't exist
          mkdir -p Builds/MacOSX
        
      - name: Build Plugin
        run: |
          # Navigate to the Xcode project directory created by Projucer
          cd QuackerVST/Builds/MacOSX
          
          # List contents to debug
          echo "Contents of generated Xcode project directory:"
          ls -la
          
          # Build the project using the correct project name from the .jucer file
          xcodebuild -project TremoloViola.xcodeproj -configuration "Release" -jobs 4
          
      - name: Package Plugin
        run: |
          # Create directory for packaging
          mkdir -p package/VST3
          mkdir -p package/AU
          
          # List build outputs to debug
          echo "Contents of build directory:"
          ls -la QuackerVST/Builds/MacOSX/build/Release || echo "Build directory not found"
          
          # Copy plugins to the package directory
          cp -R QuackerVST/Builds/MacOSX/build/Release/TremoloViola.vst3 package/VST3/ || echo "VST3 not found"
          cp -R QuackerVST/Builds/MacOSX/build/Release/TremoloViola.component package/AU/ || echo "AU not found"
          
          # Zip the package
          cd package
          zip -r TremoloViola_Mac.zip .
          mv TremoloViola_Mac.zip ../
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TremoloViola_Mac
          path: TremoloViola_Mac.zip
          retention-days: 30
