name: Build TremoloViola Plugin

on:
  workflow_dispatch:  # This allows manual triggering via a button in the GitHub UI

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "Setting up environment variables"
          echo "JUCE_VERSION=7.0.8" >> $GITHUB_ENV
          echo "PROJECT_NAME=TremoloViolaVST" >> $GITHUB_ENV
          echo "JUCER_FILE=QuackerVST/QuackerVST.jucer" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew update
          brew install cmake
          
      - name: Download and build JUCE
        run: |
          echo "Downloading JUCE ${JUCE_VERSION}"
          curl -L -o JUCE.zip "https://github.com/juce-framework/JUCE/archive/refs/tags/${JUCE_VERSION}.zip"
          unzip JUCE.zip
          mv JUCE-${JUCE_VERSION} JUCE
          
          echo "Building Projucer"
          cd JUCE
          cmake -B build -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=ON
          cmake --build build --target Projucer --config Release
          
          echo "Projucer path:"
          ls -la build/extras/Projucer/Projucer_artefacts/

      - name: Prepare JUCER file
        run: |
          echo "Creating modified JUCER file with correct module paths"
          
          # Get absolute path to JUCE modules
          JUCE_MODULES_PATH=$(pwd)/JUCE/modules
          echo "JUCE modules path: $JUCE_MODULES_PATH"
          
          # Create a backup of the original file
          cp "${JUCER_FILE}" "${JUCER_FILE}.backup"
          
          # Use a different approach with perl for better compatibility on macOS
          perl -i -pe 's|(path=").*?(")$|${1}'$JUCE_MODULES_PATH'${2}|g' "${JUCER_FILE}"
          
          # Let's verify the changes
          echo "Changes made to JUCER file:"
          grep -A 3 "<MODULEPATH" "${JUCER_FILE}"
          
      - name: Debug JUCE structure
        run: |
          echo "Checking JUCE directory structure:"
          ls -la JUCE
          echo "Checking JUCE modules directory:"
          ls -la JUCE/modules
          
      - name: Resave JUCER file
        run: |
          echo "Resaving JUCER file using Projucer"
          ./JUCE/build/extras/Projucer/Projucer_artefacts/Projucer.app/Contents/MacOS/Projucer --resave "${JUCER_FILE}"
          
      - name: Export Xcode project
        run: |
          echo "Exporting Xcode project"
          ./JUCE/build/extras/Projucer/Projucer_artefacts/Projucer.app/Contents/MacOS/Projucer --export-xcode "${JUCER_FILE}"
          
      - name: Build VST3 plugin
        run: |
          echo "Building VST3 plugin with Xcode"
          cd QuackerVST/Builds/MacOSX
          xcodebuild -project TremoloViolaVST.xcodeproj -configuration Release -destination 'platform=macOS'
          
          echo "Checking build output"
          ls -la build/Release
          
      - name: Package plugin
        run: |
          echo "Creating ZIP archive of VST3 plugin"
          cd QuackerVST/Builds/MacOSX/build/Release
          mkdir -p TremoloViola
          cp -r "TremoloViola.vst3" TremoloViola/
          zip -r TremoloViola-macOS.zip TremoloViola
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TremoloViola-macOS
          path: QuackerVST/Builds/MacOSX/build/Release/TremoloViola-macOS.zip
